sep 05 22:45:16 fossbox systemd[1450]: Starting Pass libsecret service...
sep 05 22:45:16 fossbox pass_secret_service[16808]: Traceback (most recent call last):
sep 05 22:45:16 fossbox pass_secret_service[16808]:   File "/nix/store/lpdnnp3fp640fpg063gmci7k459358vw-pass-secret-service-0-unstable-2023-12-16/bin/.pass_secret_service-wrapped", line 9, in <module>
sep 05 22:45:16 fossbox pass_secret_service[16808]:     sys.exit(main())
sep 05 22:45:16 fossbox pass_secret_service[16808]:              ~~~~^^
sep 05 22:45:16 fossbox pass_secret_service[16808]:   File "/nix/store/hb5gh29nancv2ap57b82l5ri3r4h58h6-python3.13-click-8.1.8/lib/python3.13/site-packages/click/core.py", line 1161, in __call__
sep 05 22:45:16 fossbox pass_secret_service[16808]:     return self.main(*args, **kwargs)
sep 05 22:45:16 fossbox pass_secret_service[16808]:            ~~~~~~~~~^^^^^^^^^^^^^^^^^
sep 05 22:45:16 fossbox pass_secret_service[16808]:   File "/nix/store/hb5gh29nancv2ap57b82l5ri3r4h58h6-python3.13-click-8.1.8/lib/python3.13/site-packages/click/core.py", line 1082, in main
sep 05 22:45:16 fossbox pass_secret_service[16808]:     rv = self.invoke(ctx)
sep 05 22:45:16 fossbox pass_secret_service[16808]:   File "/nix/store/hb5gh29nancv2ap57b82l5ri3r4h58h6-python3.13-click-8.1.8/lib/python3.13/site-packages/click/core.py", line 1443, in invoke
sep 05 22:45:16 fossbox pass_secret_service[16808]:     return ctx.invoke(self.callback, **ctx.params)
sep 05 22:45:16 fossbox pass_secret_service[16808]:            ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sep 05 22:45:16 fossbox pass_secret_service[16808]:   File "/nix/store/hb5gh29nancv2ap57b82l5ri3r4h58h6-python3.13-click-8.1.8/lib/python3.13/site-packages/click/core.py", line 788, in invoke
sep 05 22:45:16 fossbox pass_secret_service[16808]:     return __callback(*args, **kwargs)
sep 05 22:45:16 fossbox pass_secret_service[16808]:   File "/nix/store/lpdnnp3fp640fpg063gmci7k459358vw-pass-secret-service-0-unstable-2023-12-16/lib/python3.13/site-packages/pass_secret_service/pass_secret_service.py", line 56, in main
sep 05 22:45:16 fossbox pass_secret_service[16808]:     _main(path, verbose)
sep 05 22:45:16 fossbox pass_secret_service[16808]:     ~~~~~^^^^^^^^^^^^^^^
sep 05 22:45:16 fossbox pass_secret_service[16808]:   File "/nix/store/lpdnnp3fp640fpg063gmci7k459358vw-pass-secret-service-0-unstable-2023-12-16/lib/python3.13/site-packages/pass_secret_service/pass_secret_service.py", line 36, in _main
sep 05 22:45:16 fossbox pass_secret_service[16808]:     pass_store = PassStore(**({"path": path} if path else {}))
sep 05 22:45:16 fossbox pass_secret_service[16808]:   File "/nix/store/lpdnnp3fp640fpg063gmci7k459358vw-pass-secret-service-0-unstable-2023-12-16/lib/python3.13/site-packages/pass_secret_service/common/pass_store.py", line 17, in __init__
sep 05 22:45:16 fossbox pass_secret_service[16808]:     self._store = PasswordStore(*args, **kwargs)
sep 05 22:45:16 fossbox pass_secret_service[16808]:                   ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
sep 05 22:45:16 fossbox pass_secret_service[16808]:   File "/nix/store/vf014brjwv5m50cmk4j8jqp0yz83mh4h-python3.13-pypass-0.2.1/lib/python3.13/site-packages/pypass/passwordstore.py", line 53, in __init__
sep 05 22:45:16 fossbox pass_secret_service[16808]:     raise Exception("could not find .gpg-id file")
sep 05 22:45:16 fossbox pass_secret_service[16808]: Exception: could not find .gpg-id file
sep 05 22:45:16 fossbox systemd[1450]: pass-secret-service.service: Main process exited, code=exited, status=1/FAILURE
sep 05 22:45:16 fossbox systemd[1450]: pass-secret-service.service: Failed with result 'exit-code'.
sep 05 22:45:16 fossbox systemd[1450]: Failed to start Pass libsecret service.
